version: '3.8'

services:
  serverless:
    container_name: python_serverless
    image: lucasfrancaid/python-serverless-offline
    environment:
      HTTP_PORT: 3001
      SERVERLESS_ACCESS_KEY: <SERVERLESS_ACCESS_KEY>
      AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/app
