name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        IMAGE_NAME: python-serverless-offline
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker images
      run:
        docker build . --file ./alpine/Dockerfile --tag $DOCKER_USER/$IMAGE_NAME:alpine
        docker build . --file ./slim-buster/Dockerfile --tag $DOCKER_USER/$IMAGE_NAME:slim-buster
    - name: Push the Docker images
      run:
        docker push $DOCKER_USER/$IMAGE_NAME:alpine
        docker push $DOCKER_USER/$IMAGE_NAME:slim-buster
